# Generated by Django 6.0.6 on 2026-07-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='members',
        ),
    ]
