# Generated by Django 6.0.6 on 2026-07-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_charge', models.BooleanField(default=False)),
                ('grants_board_rights', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'offices',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='activity_status',
            field=models.CharField(blank=True, choices=[('AKTIV', 'Aktiv'), ('INAKTIV', 'Inaktiv')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_names',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='study_program',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='wine_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_daughters', to='members.member'),
        ),
        migrations.CreateModel(
            name='OfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_assignments', to='members.member')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='members.office')),
            ],
            options={
                'db_table': 'office_assignments',
            },
        ),
    ]
