# Generated by Django 6.0.6 on 2026-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_office_member_activity_status_member_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_semester',
            field=models.CharField(choices=[('SS', 'SS'), ('WS', 'WS')], default=11, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='joined_semester_year',
            field=models.PositiveSmallIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='activity_status',
            field=models.CharField(blank=True, choices=[('AKTIV', 'Aktiv'), ('INAKTIV', 'Inaktiv')], default='', max_length=20),
        ),
    ]
